#Data Source Configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lms
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

#Logger Configuration
logging:
  level:
    org.springframework.web: error
    com.perennial: debug
    org.hibernate: error
  pattern:
      console:  "%-7p %d [%t] %c %x - %m%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file: /logs/application-debug.log


