#server Configuration
server:
  port: 8081

#view Resolver configuration
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#Profile Configuration
  profiles:
    active: dev

#File Multipart Properties
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB



